[project]
channels = ["https://prefix.dev/conda-forge", "nvidia", "pytorch", "xformers"]
description = "Add a short description here"
name = "Unsloth Demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
checkxform = 'python -m xformers.info'
cudacheck = { cmd = 'python -c "import torch; print(torch.cuda.is_available()); print(torch.__version__)"', depends-on = ["checkxform"] }
start_small = { cmd = 'minimal_grpo.py', depends-on = ["cudacheck"] }
start_big = { cmd = 'python llama3_1_\(8b\)_grpo.py', depends-on = ["cudacheck"] }


[system-requirements]
cuda = "12.4"

[dependencies]
python = "3.11.9*"
black = ">=25.1.0,<26"
cuda-version = "==12.4"

[pypi-dependencies]
vllm = "==0.7.2"
xformers = "==0.0.28.post3"
trl = "==0.14.0"
torch = { version = "==2.5.1", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = "==0.20.1", index = "https://download.pytorch.org/whl/cu124" }
unsloth-zoo = "==2025.2.3"
unsloth = "==2025.2.4"
setuptools = ">=75.8.0, <76"
xgrammar = "==0.1.11"
diffusers = ">=0.32.2, <0.33"
accelerate = ">=1.3.0, <2"
bitsandbytes = ">=0.45.2, <0.46"
peft = ">=0.14.0, <0.15"
